import * as path from 'path';
import type { RagIndex, RagRecipeMetadata } from './ragIndexBuilder';
import type { RagAutomationMode, RagLanguage } from './ragTypes';

/**
 * Turns a built `RagIndex` (ragIndexBuilder.ts) plus a query into the
 * prompt section `buildLlmPrompt()`/`buildApiLlmPrompt()` (objectSpyPanel.ts)
 * inject before sending a "Start AI Code Generation" request. Zero `vscode`
 * dependency — fully unit-testable with a hand-built index.
 */

export interface RagMatch {
  id: string;
  title: string;
  body: string;
  imports?: { java?: string[]; python?: string[] };
  score: number;
  /** The recipe's own source `.md` file's absolute path — carried through
   * so a caller (objectSpyPanel.ts) can point a user at EXACTLY which
   * `.github/rag/` file a piece of generated code was traced back to. Kept
   * as the raw absolute path here (this module has no `vscode` import to
   * compute a workspace-relative one); `formatRagPromptSection()` below
   * only ever shows the plain filename (`path.basename`), never the full
   * local path, in text that's sent to the LLM. */
  filePath: string;
}

/** `automationMode` is a soft ranking signal, not a hard requirement — see
 * `retrieveRagMatches()`'s own doc comment for why. A mode-mismatched
 * recipe's score is scaled down by this factor rather than zeroed out, so
 * it still loses to an equally-relevant, correctly-moded recipe, but can
 * still surface when its actual content relevance (folder name, filename,
 * title, tags, body) is strong enough to outweigh the penalty — exactly
 * the case a bulk-imported real framework needs: a shared utility a
 * per-file, no-context LLM guess mis-tagged as "api-only" is still findable
 * from a UI Automation scenario that clearly needs it. */
const AUTOMATION_MODE_MISMATCH_PENALTY = 0.4;

/** How many raw candidates to pull from the vector store (filtered by
 * `language` only) BEFORE applying the automationMode-aware re-ranking —
 * needs to be comfortably larger than `topK` so a correctly-moded but
 * lower-raw-score recipe, and a mismatched-but-highly-relevant one, both
 * get a real chance to be compared, rather than the raw top-`topK` (by
 * un-penalized score) already excluding one of them before re-ranking
 * even runs. Cheap either way — this store is an exact linear scan over a
 * realistically dozens-to-a-few-hundred-recipe corpus (see
 * flatVectorStore.ts), not an approximate index with a real cost curve. */
const CANDIDATE_POOL_SIZE = 20;

/** Retrieves the top `topK` recipes relevant to `queryText`.
 *
 * `language` is a HARD filter — a Python-only recipe is never shown when
 * generating Java, even if its text scores well, since the resulting code
 * would be genuinely unusable (wrong syntax, an import that doesn't
 * exist), not just a worse suggestion.
 *
 * `automationMode`, by contrast, is a SOFT preference (see
 * `AUTOMATION_MODE_MISMATCH_PENALTY`) — it used to be a hard filter too,
 * but that meant a recipe generated by "Generate RAG Corpus format" (an
 * LLM guessing `automationMode` for ONE file at a time, with no knowledge
 * of how it'll later be searched) that got tagged e.g. `api`-only could
 * never surface for a UI Automation scenario even when its folder name,
 * filename, and content were an obvious, strong match — the exact "RAG
 * clearly has the right file, but never uses it" failure this exists to
 * prevent.
 *
 * A zero-or-negative final score is dropped entirely (see the filter
 * below) — sharing every indexed recipe regardless of relevance would
 * defeat the whole point (unrelated context inflating the prompt and,
 * worse, tempting the model to shoehorn in a helper that doesn't actually
 * apply). */
export async function retrieveRagMatches(
  index: RagIndex,
  queryText: string,
  language: RagLanguage,
  automationMode: RagAutomationMode,
  // Lowered from 3 to 2 — automationMode moving from a hard filter to a
  // soft preference means a query now legitimately matches MORE recipes
  // than before (mode mismatches no longer disqualify a recipe outright),
  // so the same topK now injects more total content into the prompt on
  // average than it used to. Fewer, higher-scoring components is a safer
  // default against a real provider failure mode this extension has hit in
  // practice — see runLlmRefinement()'s own retry-without-RAG fallback and
  // RAG_MAX_RECIPE_BODY_CHARS below, both hardening the SAME risk from a
  // different angle.
  topK = 2
): Promise<RagMatch[]> {
  if (!queryText.trim()) {
    return [];
  }
  const queryVector = await index.embeddings.embedQuery(queryText);
  const candidates = await index.store.similaritySearchVectorWithScore(queryVector, CANDIDATE_POOL_SIZE, { language });
  return candidates
    .map(([doc, rawScore]) => {
      const metadata = doc.metadata as RagRecipeMetadata;
      const modeMatches = (metadata.automationMode as string[]).includes(automationMode);
      const score = modeMatches ? rawScore : rawScore * AUTOMATION_MODE_MISMATCH_PENALTY;
      return { id: metadata.id, title: metadata.title, body: doc.pageContent, imports: metadata.imports, score, filePath: metadata.filePath };
    })
    .filter((match) => match.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK);
}

/** Hard safety net on a SINGLE recipe body's contribution to the prompt —
 * "Generate RAG Corpus format" (ragCorpusGenerator.ts) accepts source
 * files up to 200KB and asks Copilot to write a recipe from one, with no
 * cap on how much of that the model echoes back into the body it returns.
 * Without this, one unusually verbose auto-generated recipe (or a
 * hand-written one someone pasted a large class into) can silently make
 * "Start AI Code Generation"'s ALREADY sizeable prompt (built-in
 * instructions + every checked custom .md file + the full recorded/API
 * code) too large for the model — while "Start AI Feature File
 * Generation", which never includes RAG content at all, keeps working
 * fine with the exact same recipe library, misleadingly looking like "RAG
 * itself is broken" when the real cause is one oversized recipe tipping a
 * request that was already close to the model's own context limit.
 * Lowered from 4,000 to 1,500 for the same reason `topK` was lowered above
 * — automationMode is now a soft preference rather than a hard filter, so
 * a real request measurably injects RAG content more often than it used
 * to; a smaller per-recipe ceiling keeps the WORST case bounded even
 * against that. */
const RAG_MAX_RECIPE_BODY_CHARS = 1_500;

/** A second, TOTAL cap across every matched recipe combined — belt and
 * suspenders on top of the per-recipe cap above. `topK * RAG_MAX_RECIPE_BODY_CHARS`
 * bounds the worst case mathematically, but this catches it explicitly
 * too rather than relying on that arithmetic staying true if either
 * constant is tuned again later without updating the other. */
const RAG_MAX_TOTAL_SECTION_CHARS = 4_000;

/** Pure formatter — returns `''` (no section at all) when there's nothing
 * to show, so a request with no relevant reusable component costs exactly
 * zero extra prompt tokens, never a "no matches found" placeholder. */
export function formatRagPromptSection(matches: RagMatch[], language: RagLanguage): string {
  if (matches.length === 0) {
    return '';
  }

  const importLines = Array.from(
    new Set(
      matches
        .map((match) => match.imports?.[language])
        .filter((imports): imports is string[] => Array.isArray(imports) && imports.length > 0)
        .flat()
    )
  );

  const parts = [
    '\n## Reusable components available — prefer these over writing new code',
    "Your team maintains a library of tested, reusable helpers. Before writing new logic for something one of " +
      'these already does, USE IT: add the exact import statement shown below, then call the helper exactly as ' +
      "shown in its example. Do not reimplement what's already here, and do not modify a helper's own " +
      'implementation — only call it. TRACEABILITY (required): the FIRST TIME you call any component listed ' +
      'below, add a one-line comment directly above that call, in this exact form (using this language\'s own ' +
      'comment syntax): "RAG match: <component id> (from <source file>)" — using the exact id and source file ' +
      'shown for that component below. This lets a reviewer see, directly in the generated code, that this call ' +
      "came from the team's own reusable library rather than being freshly written."
  ];
  matches.forEach((match, i) => {
    const body =
      match.body.length > RAG_MAX_RECIPE_BODY_CHARS
        ? `${match.body.slice(0, RAG_MAX_RECIPE_BODY_CHARS)}\n… (truncated — this recipe's body is unusually large; consider trimming it in .github/rag/)`
        : match.body;
    parts.push(`\n### ${i + 1}. ${match.title} (id: \`${match.id}\`, source file: \`${path.basename(match.filePath)}\`)`, body);
  });
  if (importLines.length > 0) {
    parts.push(`\n### Required imports for the component(s) used above\n${importLines.map((line) => `\`${line}\``).join('\n')}`);
  }
  const section = parts.join('\n');
  if (section.length > RAG_MAX_TOTAL_SECTION_CHARS) {
    return `${section.slice(0, RAG_MAX_TOTAL_SECTION_CHARS)}\n… (RAG section truncated at ${RAG_MAX_TOTAL_SECTION_CHARS.toLocaleString()} total chars — a hard safety cap; consider trimming .github/rag/ recipes or reducing how many match.)`;
  }
  return section;
}
